import type { Snapshot } from "@/generator/lib/Snapshot/SnapshotTypes";

const createBaseSnapshot = (directus: string, version: number): Snapshot => {
  const snapshot: Snapshot = {
    collections: [
      {
        collection: `_prisma_migrations`,
        meta: {
          accountability: `all`,
          archive_app_filter: true,
          archive_field: null,
          archive_value: null,
          collapse: `open`,
          collection: `_prisma_migrations`,
          color: null,
          display_template: null,
          group: null,
          hidden: true,
          icon: null,
          item_duplication_fields: null,
          note: null,
          preview_url: null,
          singleton: false,
          sort: null,
          sort_field: null,
          translations: null,
          unarchive_value: null,
          versioning: false,
        },
        schema: {
          name: `_prisma_migrations`,
        },
      },
    ],
    directus,
    fields: [
      {
        collection: `_prisma_migrations`,
        field: `applied_steps_count`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `applied_steps_count`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: true,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `integer`,
          default_value: 0,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: false,
          is_primary_key: false,
          is_unique: false,
          max_length: null,
          name: `applied_steps_count`,
          numeric_precision: 32,
          numeric_scale: 0,
          table: `_prisma_migrations`,
        },
        type: `integer`,
      },
      {
        collection: `_prisma_migrations`,
        field: `checksum`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `checksum`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `character varying`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: false,
          is_primary_key: false,
          is_unique: false,
          max_length: 64,
          name: `checksum`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `string`,
      },
      {
        collection: `_prisma_migrations`,
        field: `finished_at`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `finished_at`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `timestamp with time zone`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: true,
          is_primary_key: false,
          is_unique: false,
          max_length: null,
          name: `finished_at`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `timestamp`,
      },
      {
        collection: `_prisma_migrations`,
        field: `id`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `id`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `character varying`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: false,
          is_primary_key: true,
          is_unique: true,
          max_length: 36,
          name: `id`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `string`,
      },
      {
        collection: `_prisma_migrations`,
        field: `logs`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `logs`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `text`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: true,
          is_primary_key: false,
          is_unique: false,
          max_length: null,
          name: `logs`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `text`,
      },
      {
        collection: `_prisma_migrations`,
        field: `migration_name`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `migration_name`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `character varying`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: false,
          is_primary_key: false,
          is_unique: false,
          max_length: 255,
          name: `migration_name`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `string`,
      },
      {
        collection: `_prisma_migrations`,
        field: `rolled_back_at`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `rolled_back_at`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `timestamp with time zone`,
          default_value: null,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: true,
          is_primary_key: false,
          is_unique: false,
          max_length: null,
          name: `rolled_back_at`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `timestamp`,
      },
      {
        collection: `_prisma_migrations`,
        field: `started_at`,
        meta: null,
        // meta: {
        //   collection: `_prisma_migrations`,
        //   conditions: null,
        //   display: null,
        //   display_options: null,
        //   field: `started_at`,
        //   group: null,
        //   hidden: false,
        //   interface: null,
        //   note: null,
        //   options: null,
        //   readonly: false,
        //   required: false,
        //   sort: null,
        //   special: null,
        //   translations: null,
        //   validation: null,
        //   validation_message: null,
        //   width: `full`,
        // },
        schema: {
          data_type: `timestamp with time zone`,
          default_value: `now()`,
          foreign_key_column: null,
          foreign_key_table: null,
          generation_expression: null,
          has_auto_increment: false,
          is_generated: false,
          is_nullable: false,
          is_primary_key: false,
          is_unique: false,
          max_length: null,
          name: `started_at`,
          numeric_precision: null,
          numeric_scale: null,
          table: `_prisma_migrations`,
        },
        type: `timestamp`,
      },
    ],
    relations: [],
    vendor: `postgres`,
    version,
  };

  return snapshot;
};

export { createBaseSnapshot };
