import { z } from "zod";

import { ConditionDictionary } from "prisma-directus-generator/lib/Generator/Condition";
import { FilterDictionary } from "prisma-directus-generator/lib/Generator/Filter";
import { RichTextCustomSyntax } from "prisma-directus-generator/lib/Generator/RichTextCustomSyntax";

const GeneratorConfig = z
  .object({
    banner: z
      .string()
      .default(
        `# This file was generated by Prisma Directus Generator. Do not edit manually.`,
      ),
    conditions: ConditionDictionary.default({}),
    debugFile: z.string().optional(),
    directivePrefix: z.string().default(`@`),
    directus: z.string(),
    filters: FilterDictionary.default({}),
    folders: z
      .record(
        z.object({
          id: z.string().uuid(),
        }),
      )
      .default({}),
    includePrismaMigrations: z.boolean().default(false),
    layoutsFile: z.string().default(`./directus-layouts.yml`),
    permissionsFile: z.string().default(`./directus-permissions.yml`),
    richTextCustomSyntaxes: z.array(RichTextCustomSyntax).default([]),
    roles: z.record(
      z
        .object({
          id: z.string().uuid().nullable(),
        })
        .strict(),
    ),
    snapshotFile: z.string().default(`./directus-snapshot.yml`),
    traceFile: z.string().optional(),
    transformAliasFieldName: z.enum([`camelCase`, `snake_case`]).optional(),
    version: z.number().int().nonnegative(),
  })
  .strict();
type GeneratorConfig = z.infer<typeof GeneratorConfig>;

export { GeneratorConfig };
