import { mkdir, readFile, writeFile } from "fs/promises";
import { dirname } from "path";
import { inspect } from "util";

import generatorHelper from "@prisma/generator-helper";
import prismaInternals from "@prisma/internals";
import { dump, load } from "js-yaml";
import { z } from "zod";

import {
  Config,
  createDefaultConfig,
  mergeConfig,
} from "@/generator/lib/Config";
import { createSnapshot } from "@/generator/lib/Snapshot/Snapshot";

const GeneratorConfig = z
  .object({
    autoSortFields: z.boolean().default(false),
    banner: z
      .string()
      .default(
        `# This file was generated by Prisma Directus Generator. Do not edit manually.`,
      ),
    configFile: z.string().optional(),
    debugFile: z.string().optional(),
    directivePrefix: z.string().default(`@`),
    directus: z.string(),
    errorFile: z.string().optional(),
    version: z.coerce.number(),
  })
  .strict();
type GeneratorConfig = z.infer<typeof GeneratorConfig>;

const { generatorHandler } = generatorHelper;
const { parseEnvValue } = prismaInternals;

const parseConfigFile = async (configFile?: string): Promise<Config> => {
  const defaultConfig = createDefaultConfig();
  if (typeof configFile === `undefined`) {
    return defaultConfig;
  }
  const configString = await readFile(configFile, `utf-8`);
  const configObj: unknown =
    configFile.endsWith(`.yml`) || configFile.endsWith(`.yaml`)
      ? load(configString)
      : JSON.parse(configString);
  const config = Config.parse(configObj);
  return mergeConfig(defaultConfig, config);
};

const generate = () =>
  generatorHandler({
    onGenerate: async ({ dmmf, generator }) => {
      if (!generator.output) {
        throw new Error(`No output directory specified`);
      }
      const {
        autoSortFields,
        banner,
        configFile,
        debugFile,
        directivePrefix,
        directus,
        errorFile,
        version,
      } = GeneratorConfig.parse(generator.config);

      const config = await parseConfigFile(configFile);

      const { error, isError, snapshot } = createSnapshot({
        autoSortFields,
        conditions: config.conditions,
        datamodel: dmmf.datamodel,
        directivePrefix,
        directus,
        filters: config.filters,
        version,
      });

      if (isError) {
        if (typeof debugFile === `string`) {
          await writeFile(debugFile, `${banner}\n${dump(snapshot)}`);
        }
        if (typeof errorFile === `string`) {
          await writeFile(errorFile, inspect(error, { depth: null }));
        }
        throw error;
      }

      const outputPath = parseEnvValue(generator.output);
      const outputDir = dirname(outputPath);

      await mkdir(outputDir, { recursive: true });
      await writeFile(outputPath, `${banner}\n${dump(snapshot)}`);
    },
    onManifest: () => ({
      defaultOutput: `./directus-snapshot.yml`,
      prettyName: `@prisma-diretus/generator`,
    }),
  });

export { generate };
